# Generated by Django 4.1.7 on 2023-04-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='topic_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.topic'),
            preserve_default=False,
        ),
    ]
