# Generated by Django 4.1.7 on 2023-04-26 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_player_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
